# Generated by Django 3.1.6 on 2021-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
