# Generated by Django 3.1.6 on 2021-05-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210515_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
