# Generated by Django 3.1.6 on 2021-05-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210521_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles'),
        ),
    ]
