# Generated by Django 3.1.6 on 2021-06-08 16:04

import api.models
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210608_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('user_picture', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to=api.models.User.upload_to),
        ),
    ]
