# Generated by Django 3.1.6 on 2021-07-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210701_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='Locations',
        ),
    ]
