# Generated by Django 3.1.6 on 2021-07-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210701_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='match_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.location'),
        ),
    ]
