# Generated by Django 3.1.6 on 2021-07-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210703_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_image_url',
            field=models.TextField(null=True),
        ),
    ]
