# Generated by Django 3.1.6 on 2021-07-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_location_location_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
