# Generated by Django 3.1.6 on 2021-07-08 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210705_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_image_url',
            field=models.TextField(null=True),
        ),
    ]
