# Generated by Django 3.1.6 on 2021-07-08 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210707_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='matches_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matches',
            name='match_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.location'),
        ),
    ]
