# Generated by Django 3.1.6 on 2021-07-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210707_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
