# Generated by Django 3.1.6 on 2021-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210707_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='sport',
            field=models.CharField(choices=[('basketball', 'Basketball'), ('soccer', 'Soccer'), ('football', 'Football'), ('tennis', 'Tennis'), ('volleyball', 'VolleyBall'), ('frisbee', 'Frisbee')], max_length=15),
        ),
        migrations.AlterField(
            model_name='matches',
            name='time',
            field=models.TimeField(),
        ),
    ]
