# Generated by Django 3.1.6 on 2021-07-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210715_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='location_city',
        ),
        migrations.AddField(
            model_name='user',
            name='location_state',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
