# Generated by Django 3.1.6 on 2021-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210728_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(max_length=4),
        ),
    ]
