# Generated by Django 3.1.6 on 2021-08-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_location_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
