# Generated by Django 3.1.6 on 2021-08-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210814_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='timezone',
        ),
    ]
