# Generated by Django 3.1.6 on 2021-08-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210814_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
