# Generated by Django 3.1.6 on 2021-08-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210814_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timezone',
            field=models.CharField(default='EST', max_length=50),
            preserve_default=False,
        ),
    ]
